### ISSUE TITLE
two laptops login same account

### ISSUE THREAD

**Issue by weihaoqu** [rohinmittal/ubsmart#43]
We use two laptops to login in the same account, we can still do that. is this the original design?

**Comment by rohinmittal** [comment]
This is a good catch considering the security aspect of the website. However, since this wasn't a part of our requirement document, we did not look into it.

@juggernaut-90 any comments on session handling?

**Comment by suramrit** [comment]
as a side note: logging even with 2 different systems will not affect the functioning of the website for the  user majorly.

**Comment by rohinmittal** [comment]
Marking as wontfix, since this is not a part of the requirement document.
