### ISSUE TITLE
No Hyperlink for Navigation

### ISSUE THREAD

**Issue by AceArthur** [rohinmittal/ubsmart#44]
![1](https://cloud.githubusercontent.com/assets/13106680/11662328/ff51e01e-9da3-11e5-9b8d-6be13b206be5.png)

Should there be hyperlink and redirect for the nagivation bar at the bottom?

**Comment by rohinmittal** [comment]
Well yes. There should be individual pages for each one of them. However, this wasn't a part of our requirements and therefore, we are yet to work on it. 

Will take it later.
