### ISSUE TITLE
Automatical Logout

### ISSUE THREAD

**Issue by AceArthur** [rohinmittal/ubsmart#45]
![image](https://cloud.githubusercontent.com/assets/13106680/11662376/4fbef1c2-9da4-11e5-9bf9-f0f23feb58ea.png)
![image](https://cloud.githubusercontent.com/assets/13106680/11662387/5a07f25a-9da4-11e5-8432-e8c2ea2e66b3.png)

Click on Electronics - Laptop, or Furniture - Table (Chair) will automatical log out instead or showing something like "No Item"?

**Comment by rohinmittal** [comment]
This has been fixed and checked-in to Github. However, we still need to update our hosted website. @juggernaut-90 could you please upload the latest git code?

Thanks.

**Comment by rohinmittal** [comment]
The website has been updated. Please verify and close this issue.

**Comment by AceArthur** [comment]
It works fine now.
