### ISSUE TITLE
Sort by doesn't work

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#46]
When I try 'sort by price or tier', there comes an error message,like this: 404.0 Not Found
![screen shot 2015-12-10 at 2 23 22 pm](https://cloud.githubusercontent.com/assets/15369053/11725846/c4b52d92-9f49-11e5-851a-7bb6bcc185e0.png)

**Comment by rohinmittal** [comment]
Please upload few products from seller account and see if it works.

**Comment by rohinmittal** [comment]
@juggernaut-90 Vaibhav, looks like we are missing some sanity check here.

**Comment by rohinmittal** [comment]
This has been fixed. Please validate.

**Comment by tguo2** [comment]
I will upload some products and validate it later. Thanks.
