### ISSUE TITLE
Only one item for selling on the website

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#47]
There is only one item for selling on the website, so we cannot test out whether the search bar works well.

**Comment by rohinmittal** [comment]
Please go through our requirements document. The project also has 'seller' feature where you can register yourself as a seller and upload products. 

We would request you to please do that since it will also help us in getting QA feedback about the seller functionality.

**Comment by tguo2** [comment]
Sure we will do that later as a seller and then test the search bar.
