### ISSUE TITLE
Cannot buy the item shows on the website

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#49]
First, when I login as buyer, the product image does't show up. It shows like that. Then, I try to click this item to buy it, but an error message comes out.
![screen shot 2015-12-10 at 3 15 25 pm](https://cloud.githubusercontent.com/assets/15369053/11727296/1b8d3f0e-9f51-11e5-97ef-eb18d695ad96.png)
![screen shot 2015-12-10 at 3 15 35 pm](https://cloud.githubusercontent.com/assets/15369053/11727319/3d445150-9f51-11e5-8b74-7d1d154be722.png)

**Comment by rohinmittal** [comment]
@juggernaut-90 Please look into it.

Thanks.

**Comment by rohinmittal** [comment]
This has been fixed. Please verify.

**Comment by tguo2** [comment]
Yes it is.
