### ISSUE TITLE
Confused about buyer and seller account

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#51]
I login as buyer to search the products, but when I click 'my account', it sometimes shows like a seller account like this.(Mostly it shows like buyer account, but occasionally shows seller account)
![screen shot 2015-12-11 at 1 45 09 pm](https://cloud.githubusercontent.com/assets/15369053/11752499/f273fa32-a00d-11e5-8ea1-82d19cd1657f.png)

**Comment by rohinmittal** [comment]
We have re-checked our session handling and login code. This appears to be some glitch. Please clean your cache, logout and try again. 

Please avoid logging from two systems with same credentials. That might be one of the reason.
