### ISSUE TITLE
0 pending handovers

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#52]
Yesterday I tried to buy a cellphone and confirmed as a buyer. It shows pending at the seller like this
![screen shot 2015-12-11 at 1 49 29 pm](https://cloud.githubusercontent.com/assets/15369053/11752620/9bc15120-a00e-11e5-9cd4-e9406bad0d3a.png)

But when I login back it shows no pending handovers like this. Is that a small bug?
![screen shot 2015-12-11 at 1 49 44 pm](https://cloud.githubusercontent.com/assets/15369053/11752639/b8b9256e-a00e-11e5-8290-1abecd25b72b.png)

**Comment by rohinmittal** [comment]
'0' pending handovers here means, the handovers you need to approve. Since you have already confirmed, it will decrement the count. 

We'll change the language to "You need to confirm <X> orders."
