### ISSUE TITLE
Have some questions about topup and encash from the virtual wallet

### ISSUE THREAD

**Issue by tguo2** [rohinmittal/ubsmart#56]
Is there any ways to test about the virtual wallet? Besides, since the current balance is 0, how can I test to buy something? Does it really have a connection between the bank account?

**Comment by rohinmittal** [comment]
Please go through our requirement document again. As of now, we have not linked the project with a bank account (otherwise testing would have become really troubling. :) ) You can still enter a random CC number, top up your virtual wallet and shop.
