### ISSUE TITLE
Laptop and Iphone disappear

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#57]
![qq 20151214130531](https://cloud.githubusercontent.com/assets/14227790/11789426/51907b1e-a264-11e5-9ec7-0a6474446435.png)
after I have bought these two things, they disappear. 
And after I register other account, they are still missing. 
Is there a bug or just for the shopping rules that once sold out, not showing up again?

**Comment by vaibhavsinha90** [comment]
Yes. We have always assumed quantity=1 for any uploaded product. Once sold,
it will not show up again.
