### ISSUE TITLE
As seller, upload a product, edit its information, and it disappear.

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#61]
![2](https://cloud.githubusercontent.com/assets/14227790/11790369/6273fffa-a269-11e5-962e-140070c9731d.png)
![3](https://cloud.githubusercontent.com/assets/14227790/11790368/627318b0-a269-11e5-85a8-48ee413a3e36.png)
As titled.

**Comment by suramrit** [comment]
Will look into it. Till then can you please verify whether both the 'delete product' and 'edit product' features have issue or just the edit product one.
