### ISSUE TITLE
One critic issue

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#62]
As the featured functionality, the Smart price gives us the suggestion about the negotiating the price. 
So I have several questions about the Smart price.
1, what is the different between smart price and the price made by the seller?
2, how to calculate it? I mean, if we want to test the functionality of the smart price, what should we do?

**Comment by suramrit** [comment]
Here are few basic points that I hope will clear your doubts.
Smart Price takes into consideration several aspects of the product (category, condition, current price range for similar products) and comes up with a price that it evaluates to be a fair reflection of the price that such a product can be sold at. Thus it has little correlation to the price asked by the seller. This gives a buyer sufficient information to evaluate whether the price asked by seller is fair or not, he can then negotiate with the buyer (who already knew about the smart price while uploading the product).

**Comment by jianmengpei** [comment]
I might understand what it would run, but I want to run it practically. Actually, if you have the equation of the Smart Price, that would also fine.
