### ISSUE TITLE
Why searching "iph%%one" succeeds?

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#63]
![qq 20151214140218](https://cloud.githubusercontent.com/assets/14227790/11790749/5814c4ac-a26b-11e5-93fa-e3c4b942965a.png)

**Comment by vaibhavsinha90** [comment]
The search system inherently supports SQL type wildcards/regex

**Comment by suramrit** [comment]
I would consider this as a robust feature of our system :+1:
