### ISSUE TITLE
How many iphones does the system to calculate the Smart Price

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#64]
I have upload 5 iphones, but the Smart Price still is 0. If you keep the how to calculate the Smart Price secret, just tell me what is the amount the system needs to obtain the Smart Price.

**Comment by suramrit** [comment]
I would suggest you also buy certain products. As mentioned elsewhere it does not necessarily depend on the price at which a product is uploaded by the seller. Hope this helps .

**Comment by jianmengpei** [comment]
OK, here is the thing. I upload 5, and buy 5. And then the smart price is still 0.
Is it normal? Or it is a bug.
I just want to know what is the number I need to buy or sell. Please don't concern about the business secret or other things. I just want to have a test about the smart price. You said "certain" and "a mount". If you still can not give me a number, after I have tried 5 times, it is still 0. Now, I am gonna treat this Smart Price as a bug.

**Comment by vaibhavsinha90** [comment]
Please ensure that the handover is confirmed by both buyer and seller for
the product purchased by you. Unless both have confirmed, SmartPrice will
not be updated

**Comment by jianmengpei** [comment]
OK, I would try more.
