### ISSUE TITLE
After I refresh at the Upload Product Page, things might be missed up

### ISSUE THREAD

**Issue by jianmengpei** [rohinmittal/ubsmart#66]
![12222](https://cloud.githubusercontent.com/assets/14227790/11804238/6299fac2-a2d0-11e5-8d5e-edeefb6aa672.png)

**Comment by suramrit** [comment]
Yes. The radio buttons do take their default values. But rest of the field values remain consistent.

**Comment by rohinmittal** [comment]
Hi QA Team,

As the deadline is approaching, please let us know the issues that are urgent as per your understanding. I would request you to please keep cosmetic issues aside for now and if you find any major functionality issue, let us know asap so that we can go ahead and do the fix.

Thanks.
